### PR TITLE
Remove hardcoded filter for files ending in tilde

### LINKED ISSUE #2115: Folders ending with the '~' character are not synced
MCV example:

Create a folder to be synced. I called mine `Test`.
Inside it create a folder called `Folder~`.
Inside `Folder~`, create any file.

When syncing the folder `Test`, the folder `Folder~` is ignored.

Google suggests that this is intentional behavior because you want to prevent syncing of temporary files. Can you make this a config option or reconsider it altogether? As a file synchronization service I don't expect Seafile to be determining what should be filtered and what shouldn't. If a file is in a directory marked for synchronization then I expect it to be synced, and if temp files get synced then that's my problem.

### PR DESCRIPTION
**Pull request by samczsun**
Resolves #2115

### CODE REVIEW

**Comment by freeplant** [comment]
I changed the issue to feature request with low priority. Simply remove the filter is not the solution. I will leave the PR open.

**Comment by killing** [comment]
I think in most cases *~ files should be ignored. We don't want to provide too many options which will confuse users.

**Comment by shoeper** [comment]
> I think in most cases *~ files should be ignored.

I think in that case it should at least be documented in the user manual and it would still be good to have a way to to enable synchronization of such files. Maybe using the settings dialog as it is done with lock files. I agree, that this is low priority, though.

**Comment by allefeld** [comment]
I agree, this should at least be documented.

Also, is this related to the option "enable sync temporary files of MSOffice/Libreoffice" in the GUI client? If not, maybe subsuming it under this would be an option. Just make a general option "enable sync temporary files", and document how it is determined that a file is temporary.

**Pull request closed without merging**
