### PR TITLE
[scripts] fixed upgrade_4.3_4.4.sh

### PR DESCRIPTION
**Pull request by lins05**

### CODE REVIEW

**Comment by shoeper** [comment]
What is the key being used for?

**Comment by freeplant** [comment]
It is used in two or three places. One place is as one of the random number for generating the password reset token.

**Comment by shoeper** [comment]
Ok, thanks. At least for that it would be a feature to regenerate it from 
time to time, wouldn't it? Another thing is that generating passwords would 
be more secure by using e.g. openssl.


Am 21. Oktober 2015 10:21:46 schrieb Daniel Pan <notifications@github.com>:

**Comment by freeplant** [comment]
The logic is in the Django framework.

**Pull request merged**
