### PR TITLE
Add support to ppc64le

### PR DESCRIPTION
**Pull request by gururajrkatti**
This PR adds CI support for ppc64le architecture. Continuously building and testing on this architecture along with intel will ensure that we detect /fix any issues earlier and are always up-to-date.

### CODE REVIEW

**Comment by gururajrkatti** [comment]
Hi, just wanted to check if you got a chance to look into this

**Comment by killing** [comment]
Sorry but no longer use TravisCI. We switched to Github Actions.

**Comment by gururajrkatti** [comment]
@killing Thanks for the response and feedback. Travis does want to continue open source support Pl. refer to https://blog.travis-ci.com/oss-announcement if that is the concern

**Comment by killing** [comment]
Closing this PR as we have switched to Github Actions.

**Pull request closed without merging**
