### PR TITLE
Add option to set fastcgi/gunicorn bind address

### PR DESCRIPTION
**Pull request by Mic92**
Adding an option to set the seahub bind address, allow it to run seahub and the webserver on different machines. This is especially useful for linux container such as lxc or docker.

### CODE REVIEW

**Comment by Mic92** [comment]
bump

**Comment by Mic92** [comment]
@killing @lins05

**Comment by Mic92** [comment]
Any comments?

**Comment by freeplant** [comment]
I think seafile-admin is only used in self-compiled scenario. For packaged version, it is not used.

**Comment by Mic92** [comment]
I assume by packed version, you mean the debian package. They include this file, when the server variant is build: https://github.com/haiwen/seafile/blob/master/tools/Makefile.am#L16

It doesn't look like seafile is package the server: https://github.com/haiwen/seafile/blob/master/debian/rules

**Comment by Mic92** [comment]
Ah my postgres database is also now broken after the update and the upstream does not accept pull request for migrations scripts. I'm done with this software!

**Pull request closed without merging**
